### ISSUE TITLE
Error creating consumer using 1.1, 1.2-SNAPSHOT and Akka 2.2

### ISSUE THREAD

**Issue by hmbadiwe** [sstone/amqp-client#22]
I'm migrating my project to Akka 2.2 and whenever I try to create a consumer from a RabbitMQ connection, I get this error : 

Exception in thread "main" java.lang.NoSuchMethodError: akka.pattern.AskSupport.ask(Lakka/actor/ActorRef;)Lakka/pattern/AskSupport$AskableActorRef;
    at com.github.sstone.amqp.RabbitMQConnection.createChild(ConnectionOwner.scala:103)
    at com.github.sstone.amqp.RabbitMQConnection.createConsumer(ConnectionOwner.scala:114)
.....

shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[NormalizationActorSystem]
java.lang.NoSuchMethodError: akka.actor.ActorContext.children()Lscala/collection/Iterable;
    at com.github.sstone.amqp.ConnectionOwner$$anonfun$4.applyOrElse(ConnectionOwner.scala:227)
    at com.github.sstone.amqp.ConnectionOwner$$anonfun$4.applyOrElse(ConnectionOwner.scala:196)

It seems that the ActorRef is not supporting the ask method for retrieving futures.
This is strange because I can't find anything regarding a change in the way Akka handles futures in 2.2.

Thanks.

**Comment by sstone** [comment]
I suspect that you compile your program with akka 2.2 using a version of amqp-client compiled against akka 2.1.4. The code in branch scala2.10 is compatible with akka 2.2 but published versions (to maven central for releases and sonatype for snapshots) are compiled against akka 2.1.X
=> for now, you have to update the pom, change akka version to 2.2 and compile amqp-client yourself. Can you please try this and tell me if it works for you ?
Thanks!

**Comment by hmbadiwe** [comment]
This worked for me. Thanks!
Keep up the good work.
I was wondering, when will an akka 2.2 snapshot be published?

**Comment by sstone** [comment]
Soon :-) The thing is right now most users (including us) are still on akka 2.1.X (see the comments on issue #18), but it's coming. I will update issue #18 as soon as it's done.
Thanks!
